import Head from 'next/head';
import Link from 'next/link';
import { useSelector } from 'react-redux';

const Layout = ({children}) => {
    const { isLoggedIn } = useSelector(state => state);

    return (
        <div>
            <Head>
                <title>Chatty</title>
                <meta name="description" content="Generated by create next app" />
                <link rel="icon" href="/favicon.ico" />
            </Head>

            <main className="main flex">
                { 
                    isLoggedIn &&
                    <Link href="/accounts/logout">
                        <a className="logout">
                            <svg className="w-6 h-6" fill="none" stroke="#333" viewBox="0 0 24 24" xmlns="http://www.w3.org/2000/svg">
                                <path strokeLinecap="round" strokeLinejoin="round" strokeWidth={2} d="M17 16l4-4m0 0l-4-4m4 4H7m6 4v1a3 3 0 01-3 3H6a3 3 0 01-3-3V7a3 3 0 013-3h4a3 3 0 013 3v1" />
                            </svg>
                        </a>
                    </Link>
                }
                { children }
            </main>
        </div>
    )
}

export default Layout;