export const SET_LOGGED_IN = "SET_LOGGED_IN";
export const SET_USER_INFO = "SET_USER_INFO";
export const SET_HOST_INFO = "SET_HOST_INFO";

export const SHOW_MESSAGE_MODAL = "SHOW_MESSAGE_MODAL";
export const HIDE_MESSAGE_MODAL = "HIDE_MESSAGE_MODAL";
export const SHOW_ADD_FRIEND_MODAL = "SHOW_ADD_FRIEND_MODAL";
export const HIDE_ADD_FRIEND_MODAL = "HIDE_ADD_FRIEND_MODAL";