import Head from 'next/head';
import { authenticate } from "middlewares/authenticate";

import wrapper from 'redux/index';
import { setUserId, setLoggedIn, setUserInfo } from 'redux/actions/authenticateActions';

import Profile from 'components/profile';
import LoginForm from 'components/forms/LoginForm';
import MainSection from 'components/MainSection';

const Home = ({ isLoggedIn }) => {
  return (
    <div>
      <Head>
        <title>Chat App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main>
        { 
          isLoggedIn ?
            <div>
              <Profile />
              <MainSection />
            </div> :
            <LoginForm />
        }
      </main>
    </div>
  )
}

Home.getInitialProps = wrapper.getInitialPageProps(store => authenticate(async (context) => {
  const { req } = context;

  const userId = req.cookieUserId;

  if(userId) {
    const response = await fetch("http://localhost:3000/api/user", {
      method: "POST",
      headers: {"Content-Type": "application/json"},
      body: JSON.stringify({userId: userId}),
    });

    if(response.ok) {
      const { userData } = await response.json();
      store.dispatch(setUserId(userId));
      store.dispatch(setLoggedIn(true));
      store.dispatch(setUserInfo(userData));

      return { isLoggedIn: true };
    }
  }

  return { isLoggedIn: false };

}));

export default Home;